#!/bin/bash

mullvad_notify="notify-send -i ~/.config/i3/blocklets/img/mullvad.png -h string:x-canonical-private-synchronous:i3bvpn"

# If block is clicked
case $BLOCK_BUTTON in
1) # Left Click
  # Manage dropdown with rofi
  option=`echo -e "Connect\nDisconnect" \
    | rofi \
    -hover-select -me-select-entry '' -me-accept-entry MousePrimary \
    -theme-str 'window {width: 10%; y-offset: '"$BLOCK_Y"'px; x-offset: '"$BLOCK_X"'px;}' \
    -theme-str 'listview {scrollbar: false;}' \
    -theme-str 'inputbar {enabled: false;}' \
    -theme-str 'message {border: false;}' \
    -dmenu \
    -l 2 \
    -location 1 \
    -mesg "Mullvad VPN"`
  case $option in
     Connect)
	       $mullvad_notify "Connecting to Mullvad"
	       mullvad connect
	       while mullvad status | grep -q 'Connecting\|Disconn'; do
	       	sleep 1
	       done
	       $mullvad_notify "$(mullvad status -l)"
         ;;
     Disconnect)
	       $mullvad_notify "Disconnecting from Mullvad"
	       mullvad disconnect
	       while mullvad status | grep -q 'Disconnecting'; do
	       	sleep 1
	       done
	       sleep 1
	       $mullvad_notify "$(mullvad status -l)"
         ;;
  esac
	;;
esac

if mullvad_status=$(mullvad status); then
	if echo "$mullvad_status" | grep -q Connected; then
		location=$(echo "$mullvad_status" | awk -F 'in' '{print $2}' | xargs)
    output="  $location"
		color="#CF9A08"
	else
    output="  Disconnected"
		color="#A5351D"
	fi
else
  echo "ERR"
fi

echo "{\"full_text\":\"${output}\", \"color\":\"${color}\"}"
