# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion  ]] && \
    . /usr/share/bash-completion/bash_completion

# Use tab to cycle through completion options
# bind '"\C-i": menu-complete'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

PS1='[\u@\h \W]\$ '

# add ~/bin/ to PATH
export PATH=$PATH:~/bin/

# add ~/.local/bin to path
export PATH=$PATH:~/.local/bin/

# source scripts from ~/bin/
source ~/bin/bashFunctions.sh

# adjust mouse speed
fixRazerMouseSpeed

# custom bash prompt
source ~/bash_prompt

# execute ~/.xinitrc on login
if [ -z "${DISPLAY}"  ] && [ "${XDG_VTNR}" -eq 1  ]; then
    exec startx
fi
